### ISSUE TITLE
Error scatter pytorch

### ISSUE THREAD

**Issue by Ehteshamciitwah** [yiyixuxu/polyloss-pytorch#4]
Hello,

While making one-hot encoding of labels. I got these types of errors at scatter PyTorch. 

/opt/conda/conda-bld/pytorch_1646756402876/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [66,0,0], thread: [5,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed. 

Note : My labels is a mask with classes=2 and ignore_index=255 (label.unique()=[0,1,255]

**Comment by yiyixuxu** [comment]
Hi:

`ignore_index` is not supported here

**Comment by Ehteshamciitwah** [comment]
Thank you for your reply.
